import {
  authorization_code,
  issuer,
  me_after_url_canonicalization,
  scope,
  state
} from '@jackdbd/indieauth/schemas'
import { Static, Type } from '@sinclair/typebox'

/**
 * Query string built by the authorization endpoint.
 *
 * If the user approves the request, the authorization endpoint generates an
 * authorization code and builds the redirect back to the client.
 *
 * @see [Authorization Response - IndieAuth](https://indieauth.spec.indieweb.org/#authorization-response)
 * @see [Authorization Response - The OAuth 2.0 Authorization Framework (RFC 6749)](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2)
 */
export const authorization_response_querystring = Type.Object(
  {
    /**
     * Authorization code generated by this authorization endpoint.
     */
    code: authorization_code,

    /**
     * Issuer identifier of this authorization endpoint.
     */
    iss: Type.Optional(issuer),

    /**
     * Parameter 'state' set by the client in the request. It MUST be set to the
     * exact value that the client set in the request.
     */
    state
  },
  {
    title: 'Authorization Response Query String',
    description: `Query string built by the authorization endpoint. If the user approves the request, the authorization endpoint generates an authorization code and builds the redirect back to the client.`
  }
)

export type AuthorizationResponseQuerystring = Static<
  typeof authorization_response_querystring
>

// This is the response body to a request that asks to validate an authorization
// code. I can't find the link to the appropriate terminology
export const authorization_response_body_success = Type.Object({
  me: me_after_url_canonicalization,
  scope: Type.Optional(scope)
})

export type AuthorizationResponseBodySuccess = Static<
  typeof authorization_response_body_success
>

export const profile_url_response_body_success = Type.Object({
  me: me_after_url_canonicalization
})

export type ProfileUrlResponseBodySuccess = Static<
  typeof profile_url_response_body_success
>
