import { authorization_code } from "@jackdbd/oauth2";
import { Static, Type } from "@sinclair/typebox";
import {
  authorization_code_immutable_record,
  authorization_code_mutable_record,
  authorization_code_props,
} from "./authorization-code.js";

/**
 * Function that retrieves an authorization code from a storage backend.
 */
export const retrieveAuthorizationCode = Type.Function(
  [authorization_code],
  Type.Promise(
    Type.Union([
      authorization_code_immutable_record,
      authorization_code_mutable_record,
    ])
  ),
  {
    title: "retrieveAuthorizationCode",
    description: `Function that retrieves an authorization code from a storage backend.`,
  }
);

/**
 * Function that retrieves an authorization code from a storage backend.
 */
export type RetrieveAuthorizationCode = Static<
  typeof retrieveAuthorizationCode
>;

/**
 * Handler that runs after the authorization code has been verified.
 * You should use this handler to inform your storage backend that the
 * authorization code has been used.
 */
export const onAuthorizationCodeVerified = Type.Function(
  [authorization_code],
  Type.Promise(Type.Void()),
  {
    title: "onAuthorizationCodeVerified",
    description: `Handler that runs after the authorization code has been verified. You should use this handler to inform your storage backend that the authorization code has been used.`,
  }
);

/**
 * Handler that runs after the authorization code has been verified.
 * You should use this handler to inform your storage backend that the
 * authorization code has been used.
 */
export type OnAuthorizationCodeVerified = Static<
  typeof onAuthorizationCodeVerified
>;

/**
 * Handler executed after the user approves the authorization request on the
 * consent screen.
 * You should use it to persist the authorization code generated by the
 * authorization endpoint into your storage backend.
 */
export const onUserApprovedRequest = Type.Function(
  [authorization_code_props],
  Type.Promise(Type.Void()),
  {
    title: "onUserApprovedRequest",
    description: `Handler executed after the user approves the authorization request on the consent screen. You should use it to persist the authorization code generated by the authorization code generated by the authorization endpoint into your storage backend.`,
  }
);

/**
 * Handler executed after the user approves the authorization request on the
 * consent screen.
 * You should use it to persist the authorization code generated by the
 * authorization endpoint into your storage backend.
 */
export type OnUserApprovedRequest = Static<typeof onUserApprovedRequest>;
